name: ubuntu

on:
  pull_request:

  push:
    branches:
      - staging
      - trying

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 2.3.8, 2.4.9, 2.5.7, 2.6.5 ]
        rgv: [ master, v3.0.6 ]
        bundler_version: [ 2.2.0.dev, 3.0.0 ]
    steps:
      - uses: actions/checkout@v1
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Prepare dependencies
        run: |
          sudo apt-get install graphviz -y
          gem i parallel_tests -v "~> 2.29"
          bin/rake override_version
          bin/rake spec:parallel_deps
      - name: Run Test
        run: bin/parallel_rspec spec
        env:
          RGV: ${{ matrix.rgv }}
          BUNDLER_SPEC_SUB_VERSION: ${{ matrix.bundler_version }}
      - name: Run Test with realworld
        run: |
          bin/rake spec:realworld
        env:
          BUNDLER_SPEC_PRE_RECORDED: 1 
    timeout-minutes: 60
