language: ruby
dist: xenial
script: rake spec:travis
before_script:
  - travis_retry rake -E 'module ::Bundler; VERSION = "0.0.0"; end' override_version
  - travis_retry rake spec:travis:deps
  - travis_retry rake man:build
  - travis_retry rake spec:rubygems:clone_rubygems_$RGV

branches:
  only:
    - master
    - staging
    - trying
    - /.+-dev$/
    - /.+-stable$/

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: JxBi7DDJGkIF/7f/FSN/HUHpvV4EKfQccZHTPd1b2pNJn3GXo6u+tNVbAw2WjxYzPyPQI3ZcYBCU9SEXp/i7VmG8uMzh8Kyildw+miSKYKVb90uYqcsXWzbxwyNBgJLvyDkzST45H5lgnyAicee3WkFes/WDZikIajbH7ztdb04=

addons:
  code_climate:
    repo_token:
      secure: "TrzIv116JLGUxm6PAUskCYrv8KTDguncKROVwbnjVPKTGDAgoDderd8JUdDEXrKoZ9qGLD2TPYKExt9/QDl71E+qHdWnVqWv4HKCUk2P9z/VLKzHuggOUBkCXiJUhjywUieCJhI3N92bfq2EjSBbu2/OFHqWOjLQ+QCooTEBjv8="

rvm:
  - 2.6.1
  - 2.5.3
  - 2.4.5
  - 2.3.8

stages:
  - linting
  - test

# Rubygems versions MUST be available as rake tasks
# see Rakefile:125 for the list of possible RGV values
env:
  # We need to know if changes to rubygems will break bundler on release
  - RGV=master
  # Test the latest rubygems release with all of our supported rubies
  - RGV=v3.0.2

jobs:
  include:
    - rvm: 2.6.1
      script: rake rubocop
      stage: linting
    # Ruby 2.5, Rubygems 2.7
    - rvm: 2.5.3
      env: RGV=v2.7.8
      stage: test
    # Ruby 2.4, Rubygems 2.6
    - rvm: 2.4.5
      env: RGV=v2.6.14
      stage: test
    # Ruby 2.3, Rubygems 2.5
    - rvm: 2.3.8
      env: RGV=v2.5.2
      stage: test
    # Ruby-head (we want to know how we're doing, but not fail the build)
    - rvm: ruby-head
      env: RGV=master
      stage: test
    # 1.x mode (we want to keep stuff passing in 1.x mode for now)
    - rvm: 2.6.1
      env: RGV=v3.0.2 BUNDLER_SPEC_SUB_VERSION=1.98
      stage: test

  allow_failures:
    - rvm: ruby-head
      env: RGV=master
