before_script:
  - sudo apt-get install groff -y
  - rake spec:deps
script: rake spec:travis

rvm:
  - 1.8.7
  - 1.9.2
env:
  - RGV=v1.3.6
  - RGV=v1.3.7
  - RGV=v1.4.2
  - RGV=v1.5.3
  - RGV=v1.6.2
  - RGV=v1.7.2
  - RGV=v1.8.10
  - RGV=master

matrix:
  exclude:
    - rmv: 1.9.2
      env: RGV=v1.3.6
    - rmv: 1.9.2
      env: RGV=v1.3.7
    - rmv: 1.9.2
      env: RGV=v1.4.2

notifications:
  email:
    - travis-ci@andrearko.com
