language: ruby
dist: bionic
script:
  - bin/parallel_rspec spec
  - bin/rake spec:sudo
  - BUNDLER_SPEC_PRE_RECORDED=1 bin/rake spec:realworld

before_script:
  - travis_retry bin/rake override_version
  - travis_retry bin/rake spec:parallel_deps
  - if [ "$BUNDLER_SPEC_SUB_VERSION" = "" ];
    then
      travis_retry sudo apt-get install graphviz -y;
    fi

branches:
  only:
    - master
    - staging
    - trying
    - /.+-dev$/
    - /.+-stable$/

cache:
  directories:
    - tmp/rubocop

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: JxBi7DDJGkIF/7f/FSN/HUHpvV4EKfQccZHTPd1b2pNJn3GXo6u+tNVbAw2WjxYzPyPQI3ZcYBCU9SEXp/i7VmG8uMzh8Kyildw+miSKYKVb90uYqcsXWzbxwyNBgJLvyDkzST45H5lgnyAicee3WkFes/WDZikIajbH7ztdb04=

jobs:
  include:
    # Ruby-head (we want to know how we're doing, but not fail the build)
    - rvm: ruby-head
      env: RGV=master

  allow_failures:
    - rvm: ruby-head
      env: RGV=master
