language: ruby
script: rake spec:travis
before_script:
  - sudo apt-get install groff -y
  - rake spec:deps
notifications:
  email:
    - mail@arko.net
    - hone02@gmail.com
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#bundler"
rvm:
  # - 2.0.0-preview1 # disabled until Bundler builds on the Rails workers
  - 1.9.3
  - 1.9.2
  - 1.8.7
env:
  # Rubygems versions MUST be available as rake tasks
  # see Rakefile:66 for the list of possible RGV values
  - RGV=v1.8.24
  - RGV=v1.7.2
  - RGV=v1.6.2
  - RGV=v1.5.3
matrix:
  include:
    # Bundler 1.x supports Rubygems down to 1.3.6 on Ruby 1.8.7
    - rvm: 1.8.7
      env: RGV=v1.4.2
    - rvm: 1.8.7
      env: RGV=v1.3.7
    - rvm: 1.8.7
      env: RGV=v1.3.6
  exclude:
    # 2.0.0-preview1 shipped with Rubygems 1.8.24, so skip RGV lower than that
    - rvm: 2.0.0-preview1
      env: RGV=v1.7.2
    - rvm: 2.0.0-preview1
      env: RGV=v1.6.2
    - rvm: 2.0.0-preview1
      env: RGV=v1.5.3
