language: ruby
script: rake spec:travis
before_script:
  - travis_retry rake spec:travis:deps
  - travis_retry rake override_version
  - travis_retry rake man:build
  - travis_retry rake spec:rubygems:clone_rubygems_$RGV

# temporary workaround for https://github.com/travis-ci/travis-ci/issues/8892
group: deprecated-2017Q4

branches:
  only:
    - master
    - auto
    - /.+-dev$/
    - /.+-stable$/

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: JxBi7DDJGkIF/7f/FSN/HUHpvV4EKfQccZHTPd1b2pNJn3GXo6u+tNVbAw2WjxYzPyPQI3ZcYBCU9SEXp/i7VmG8uMzh8Kyildw+miSKYKVb90uYqcsXWzbxwyNBgJLvyDkzST45H5lgnyAicee3WkFes/WDZikIajbH7ztdb04=

addons:
  code_climate:
    repo_token:
      secure: "TrzIv116JLGUxm6PAUskCYrv8KTDguncKROVwbnjVPKTGDAgoDderd8JUdDEXrKoZ9qGLD2TPYKExt9/QDl71E+qHdWnVqWv4HKCUk2P9z/VLKzHuggOUBkCXiJUhjywUieCJhI3N92bfq2EjSBbu2/OFHqWOjLQ+QCooTEBjv8="

rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8

# Rubygems versions MUST be available as rake tasks
# see Rakefile:125 for the list of possible RGV values
env:
  # We need to know if changes to rubygems will break bundler on release
  - RGV=master
  # Test the latest rubygems release with all of our supported rubies
  - RGV=v2.7.7

matrix:
  include:
    # Ruby 2.4, Rubygems 2.6 and up
    - rvm: 2.4.2
      env: RGV=v2.6.14
    # Ruby 2.3, Rubygems 2.5 and up
    - rvm: 2.3.7
      env: RGV=v2.5.2
    - rvm: 2.3.7
      env: RGV=v2.6.14
    # Ruby-head (we want to know how we're doing, but not fail the build)
    - rvm: ruby-head
      env: RGV=master
    # 1.x mode (we want to keep stuff passing in 1.x mode for now)
    - rvm: 2.5.1
      env: RGV=v2.7.7 BUNDLER_SPEC_SUB_VERSION=1.98

  allow_failures:
    - rvm: ruby-head
      env: RGV=master
