language: ruby
script: rake spec:travis
before_script: travis_retry rake spec:travis:deps
branches:
  only:
    - master
    - 1-3-stable
    - 1-2-stable
    - 1-1-stable
    - 1-0-stable
notifications:
  email:
    # andre
    - secure: "bCcvqJT7YrBawtkXXwHhT+jOFth7r2Qv/30PkkbhQxk6Jb3xambjCOJ3U6vJ\ngYmiL50exi5lUp3oc3SEbHN5t2CrZqOZDQ6o7P8EAmB5c0oH2RrYaFOkI5Gt\nul/jGH/96A9sj0aMwG7JfdMSfhqj1DUKAm2PnnbXPL853VfmT24="
    # terence
    - secure: "MQ8eA5Jb8YzEpAo58DRGfVJklAPcEbAulpBZnTxp0am6ldneDtJHbQk21w6R\nj5GsDHlzr/lMp/GHIimtUZ7rLohfND8fj/W7fs1Dkd4eN02/ERt98x3pHlqv\nvZgSnZ39uVYv+OcphraE24QaRaGWLhWZAMYQTVe/Yz50NyG8g1U="
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#bundler"
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "geau3P+A9ZJHkA/OHN5v9Mcb8hAti1PllXw5DsHNJfLAWBAw5ReGGMA8Xfpf\nLdT7ktIUlQwzw94cKQ6sRZk8szXTiHncf3bxXTACJf2RpiKmbkoQU51TmCDq\nYSMuY1FIryk/3t9aZCrarufbIDI3DBscDEe4Bj9bERl+TJ8ArBY="
rvm:
  - 2.0.0
  - 1.9.3
# Rubygems versions MUST be available as rake tasks
# see Rakefile:66 for the list of possible RGV values
env:
  # We need to know if changes to rubygems will break bundler on release
  - RGV=master
  # Test the latest rubygems release with all of our supported rubies
  - RGV=v2.0.6
  # Test the latest stable branch so we know the next minor will work
  - RGV=2.0
matrix:
  allow_failures:
    # We want to know how we're doing with head, but not fail the build
    - rvm: ruby-head
    - env: RGV=master
    - env: RGV=2.0
    # 1.9.2 is simply too slow. it sometimes exceeds the 25m hard limit.
    - rvm: 1.9.2
    # Alternate implementations are good data points but not maintained
    - rvm: jruby
    - rvm: rbx
  include:
    # Riding the edge
    - rvm: ruby-head
      env: RGV=master
    # Alternate implementations
    - rvm: jruby
      env: RGV=v2.0.6
    - rvm: rbx
      env: RGV=v2.0.6
    # Rubygems goes down to 1.5.3 on Ruby 1.9.3
    - rvm: 1.9.3
      env: RGV=v1.8.25
    - rvm: 1.9.3
      env: RGV=v1.7.2
    - rvm: 1.9.3
      env: RGV=v1.6.2
    - rvm: 1.9.3
      env: RGV=v1.5.3
    # We only want an overview of how 1.9.2 is doing
    - rvm: 1.9.2
      env: RGV=v2.0.6
    # Rubygems goes down to 1.3.6 on Ruby 1.8.7
    - rvm: 1.8.7
      env: RGV=v1.8.25
    - rvm: 1.8.7
      env: RGV=v1.7.2
    - rvm: 1.8.7
      env: RGV=v1.6.2
    - rvm: 1.8.7
      env: RGV=v1.5.3
    - rvm: 1.8.7
      env: RGV=v1.4.2
    - rvm: 1.8.7
      env: RGV=v1.3.7
    - rvm: 1.8.7
      env: RGV=v1.3.6
