language: ruby
script: rake spec:travis
before_script:
  - rake --version
  - sudo apt-get install groff -y
  - rake spec:deps
  - gem list rake
  - rake --version
notifications:
  email:
    - mail@arko.net
    - hone02@gmail.com
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#bundler"
rvm:
  - ruby-head
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7

# Rubygems versions MUST be available as rake tasks
# see Rakefile:66 for the list of possible RGV values
env:
  - RGV=master
  - RGV=v1.8.24
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.9.2
  include:
    # Bundler 1.x supports Rubygems down to 1.5.3 on Ruby 1.9.3
    - rvm: 1.9.3
      env: RGV=v1.7.2
    - rvm: 1.9.3
      env: RGV=v1.6.2
    - rvm: 1.9.3
      env: RGV=v1.5.3
    # Bundler 1.x supports Rubygems down to 1.3.6 on Ruby 1.8.7
    - rvm: 1.8.7
      env: RGV=v1.7.2
    - rvm: 1.8.7
      env: RGV=v1.6.2
    - rvm: 1.8.7
      env: RGV=v1.5.3
    - rvm: 1.8.7
      env: RGV=v1.4.2
    - rvm: 1.8.7
      env: RGV=v1.3.7
    - rvm: 1.8.7
      env: RGV=v1.3.6
